#!/bin/bash

sshpass -p $(cat ./11.pass) ssh -q -o StrictHostKeyChecking=no -p 2220 bandit12@bandit.labs.overthewire.org 'xxd -r data.txt | gzip -d | bzip2 -d | gzip -d | tar xf - -O | tar xf - -O | bzip2 -d | tar xf - -O | gzip -d | grep -o "[0-9A-Za-z]*$"'
