#!/bin/bash

sshpass -p $(cat ./3.pass) ssh -q -o StrictHostKeyChecking=no -p 2220 bandit4@bandit.labs.overthewire.org 'find ./inhere/ -type f | while read file; do cat $file | grep "^[0-9a-zA-Z]\+$"; done;'
